In [1]:
# Importing the required libraries
import pandas as pd, numpy as np
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

F:\env\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Reading the csv file and putting it into 'df' object.
df = pd.read_csv('heart_v2.csv')

In [3]:
df.columns

Index(['age', 'sex', 'BP', 'cholestrol', 'heart disease'], dtype='object')

In [4]:
df.head()

age  sex   BP  cholestrol  heart disease
0   70    1  130         322              1
1   67    0  115         564              0
2   57    1  124         261              1
3   64    1  128         263              0
4   74    0  120         269              0

In [5]:
# Putting feature variable to X
X = df.drop('heart disease',axis=1)

# Putting response variable to y
y = df['heart disease']

In [6]:
X.head()

age  sex   BP  cholestrol
0   70    1  130         322
1   67    0  115         564
2   57    1  124         261
3   64    1  128         263
4   74    0  120         269

In [7]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: heart disease, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((189, 4), (81, 4))

In [11]:
y_train.shape, y_test.shape

((189,), (81,))

In [12]:
df.shape

(270, 5)

In [13]:
X_train.head()

age  sex   BP  cholestrol
84    57    1  110         201
251   44    1  130         219
92    54    1  124         266
201   58    1  125         300
126   62    1  120         267

In [14]:
X_test.head()

age  sex   BP  cholestrol
30    57    1  128         229
116   46    1  120         249
79    56    1  120         236
127   52    0  136         196
196   58    0  100         248

In [15]:
y_train.head()

84     0
251    0
92     1
201    1
126    1
Name: heart disease, dtype: int64

In [16]:
y_test.head()

30     1
116    1
79     0
127    0
196    0
Name: heart disease, dtype: int64

In [17]:
print(X.shape)
print(X_train.shape)
X_test.shape

(270, 4)
(189, 4)


(81, 4)

Logitstic Regression Model implementation

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
dt = LogisticRegression(random_state=0)
dt.fit(X_train, y_train)

LogisticRegression(random_state=0)

#### Evaluating model performance

In [20]:
y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
print(accuracy_score(y_train, y_train_pred))
confusion_matrix(y_train, y_train_pred)

0.708994708994709


array([[75, 26],
       [29, 59]], dtype=int64)

In [22]:
print(accuracy_score(y_test, y_test_pred))
confusion_matrix(y_test, y_test_pred)

0.654320987654321


array([[35, 14],
       [14, 18]], dtype=int64)

In [23]:
import joblib

In [24]:
joblib.dump(dt, 'lr_model')

['lr_model']

In [25]:
loaded_model = joblib.load('lr_model')

In [26]:
# initialize data of lists.
data = {'age': [60,30],
        'sex': [1,0],
        'BP' : [140,120],
        'cholestrol':[245,110]
        }
        
# Create DataFrame
new_data = pd.DataFrame(data)

In [27]:
new_data

age  sex   BP  cholestrol
0   60    1  140         245
1   30    0  120         110

In [28]:
pred = loaded_model.predict(new_data)

In [29]:
pred

array([1, 0], dtype=int64)

In [30]:
new_data['predicted'] = pred

In [31]:
new_data

age  sex   BP  cholestrol  predicted
0   60    1  140         245          1
1   30    0  120         110          0